/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    experiences: Experience;
    faqs: Faq;
    posts: Post;
    'contact-messages': ContactMessage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'pt' | 'fr' | 'es' | 'de')
    | ('en' | 'pt' | 'fr' | 'es' | 'de')[];
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'special-occasions': SpecialOccasion;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'special-occasions': SpecialOccasionsSelect<false> | SpecialOccasionsSelect<true>;
  };
  locale: 'en' | 'pt' | 'fr' | 'es' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The cruise experiences sold on the website. Each experience has a shared (per person) and a private (whole boat) rate — matching the Bókun structure.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  /**
   * URL path, e.g. "day-cruise". Stays the same in every language.
   */
  slug: string;
  /**
   * e.g. "Porto: Small-Group Douro River Day Cruise"
   */
  subtitle?: string | null;
  /**
   * e.g. "90 minutes"
   */
  duration: string;
  schedule?:
    | {
        time: string;
        id?: string | null;
      }[]
    | null;
  shared: {
    /**
     * Reference price in € per person
     */
    referencePrice?: number | null;
    /**
     * Launch price in € per person
     */
    launchPrice: number;
    shortCopy: string;
    /**
     * e.g. "Book Day Cruise"
     */
    ctaLabel: string;
  };
  private: {
    /**
     * Launch price in € per boat
     */
    launchPrice: number;
    /**
     * e.g. "Private Douro Day Cruise"
     */
    subtitle?: string | null;
    shortCopy: string;
    /**
     * e.g. "Book Private Day Cruise"
     */
    ctaLabel: string;
  };
  bokun?: {
    /**
     * The data-src URL of the Bókun calendar widget for this experience, e.g. https://widgets.bokun.io/online-sales/…/experience-calendar/1249232
     */
    widgetSrc?: string | null;
  };
  details?: {
    /**
     * e.g. "English, French, Portuguese, Spanish, German"
     */
    languages?: string | null;
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Long description. Blank lines create paragraphs.
     */
    fullDescription?: string | null;
    itinerary?:
      | {
          stop: string;
          /**
           * e.g. "Photo stop, Scenic views on the way"
           */
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    includes?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    notSuitableFor?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    notAllowed?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    knowBeforeYouGo?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Main image (hero + homepage card)
   */
  image?: (number | null) | Media;
  /**
   * Image for the private-rate card
   */
  imagePrivate?: (number | null) | Media;
  /**
   * Shown as a gallery on this experience’s detail page.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sort order on the homepage (lowest first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Practical booking questions shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Sort order within its section (lowest first)
   */
  order?: number | null;
  /**
   * Groups this question under a heading on the FAQ page.
   */
  section?: ('booking' | 'meeting-point' | 'getting-here' | 'onboard' | 'guests' | 'weather') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guides and stories about the Douro, Porto and life on the river. Good content here is what brings people to the site from Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path, e.g. "best-time-douro-river-cruise". Same across all languages.
   */
  slug: string;
  /**
   * One or two sentences shown on the blog index and in Google results.
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  category?: ('guides' | 'onboard' | 'local' | 'news') | null;
  author?: string | null;
  /**
   * Estimated reading time in minutes. Leave empty to hide.
   */
  readingMinutes?: number | null;
  /**
   * Shown as a booking call-to-action at the end of the article.
   */
  relatedExperience?: (number | null) | Experience;
  /**
   * Overrides the page title in Google. Aim for under 60 characters.
   */
  seoTitle?: string | null;
  /**
   * Meta description. Aim for 150–160 characters.
   */
  seoDescription?: string | null;
  /**
   * Comma-separated focus keywords for this article.
   */
  keywords?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the website contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  status?: ('new' | 'replied' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  duration?: T;
  schedule?:
    | T
    | {
        time?: T;
        id?: T;
      };
  shared?:
    | T
    | {
        referencePrice?: T;
        launchPrice?: T;
        shortCopy?: T;
        ctaLabel?: T;
      };
  private?:
    | T
    | {
        launchPrice?: T;
        subtitle?: T;
        shortCopy?: T;
        ctaLabel?: T;
      };
  bokun?:
    | T
    | {
        widgetSrc?: T;
      };
  details?:
    | T
    | {
        languages?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        fullDescription?: T;
        itinerary?:
          | T
          | {
              stop?: T;
              note?: T;
              id?: T;
            };
        includes?:
          | T
          | {
              item?: T;
              id?: T;
            };
        notSuitableFor?:
          | T
          | {
              item?: T;
              id?: T;
            };
        notAllowed?:
          | T
          | {
              item?: T;
              id?: T;
            };
        knowBeforeYouGo?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  image?: T;
  imagePrivate?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  section?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  author?: T;
  readingMinutes?: T;
  relatedExperience?: T;
  seoTitle?: T;
  seoDescription?: T;
  keywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit the homepage section by section. Each tab matches a block on the live page, top to bottom. Use the language selector to translate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    headline: string;
    subheadline: string;
    primaryCta: string;
    secondaryCta: string;
    mobileStickyCta: string;
    /**
     * First / main hero photo.
     */
    image?: (number | null) | Media;
  };
  campaign?: {
    /**
     * Turn off when the launch offer ends — the top banner and offer band disappear.
     */
    active?: boolean | null;
    /**
     * Shown in the top announcement bar and the offer band.
     */
    badgeText?: string | null;
    offerTitle?: string | null;
    offerBody?: string | null;
  };
  experiencesSection?: {
    /**
     * e.g. "Choose your Douro experience"
     */
    title?: string | null;
    lead?: string | null;
    /**
     * e.g. "Shared Cruises"
     */
    sharedLabel?: string | null;
    sharedTag?: string | null;
    /**
     * e.g. "Private Cruises"
     */
    privateLabel?: string | null;
    privateTag?: string | null;
  };
  route?: {
    /**
     * e.g. "From the marina to the bridges"
     */
    title?: string | null;
    lead?: string | null;
    stops?:
      | {
          stop: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Mandatory route-variation note.
     */
    note?: string | null;
    image?: (number | null) | Media;
  };
  boat?: {
    headline?: string | null;
    body?: string | null;
    specs?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  included?: {
    /**
     * e.g. "What’s included"
     */
    title?: string | null;
    /**
     * One-sentence version shown under the heading.
     */
    intro?: string | null;
    items?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  boutique?: {
    headline?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  founders?: {
    headline?: string | null;
    body?: string | null;
    /**
     * The two of them together.
     */
    image?: (number | null) | Media;
    ines?: {
      name?: string | null;
      role?: string | null;
      bio?: string | null;
      photo?: (number | null) | Media;
    };
    antonio?: {
      name?: string | null;
      role?: string | null;
      bio?: string | null;
      photo?: (number | null) | Media;
    };
  };
  faqSection?: {
    /**
     * e.g. "Frequently asked questions"
     */
    title?: string | null;
    lead?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  email: string;
  /**
   * Superseded — the contact form now sends through the transactional email API configured on the server. Messages arrive by email and are always saved under Contact Messages.
   */
  formEndpoint?: string | null;
  /**
   * WhatsApp number in international format, e.g. "+351 918 030 672"
   */
  whatsapp?: string | null;
  phones?:
    | {
        /**
         * e.g. "António" or "Bookings"
         */
        label?: string | null;
        /**
         * e.g. "+351 918 030 672"
         */
        number: string;
        id?: string | null;
      }[]
    | null;
  meetingPoint?: {
    /**
     * e.g. "Douro Marina | Afurada"
     */
    name?: string | null;
    addressLines?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
    arrivalNote?: string | null;
    /**
     * Google Maps directions link
     */
    mapsUrl?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
    google?: string | null;
  };
  bokun?: {
    /**
     * Bókun booking channel UUID used to load the widget script.
     */
    bookingChannelUUID?: string | null;
  };
  /**
   * Shown on the cancellation policy page and FAQ area.
   */
  cancellationPolicy?: string | null;
  legal?: {
    companyName?: string | null;
    /**
     * RNAAT registration number, e.g. "RNAAT 88/2002"
     */
    rnaat?: string | null;
    /**
     * Livro de Reclamações link (or leave empty for placeholder).
     */
    livroReclamacoesUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-occasions".
 */
export interface SpecialOccasion {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  intro?: string | null;
  /**
   * Short list of occasion ideas shown as bullets, e.g. "Marriage proposals".
   */
  ideas?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        primaryCta?: T;
        secondaryCta?: T;
        mobileStickyCta?: T;
        image?: T;
      };
  campaign?:
    | T
    | {
        active?: T;
        badgeText?: T;
        offerTitle?: T;
        offerBody?: T;
      };
  experiencesSection?:
    | T
    | {
        title?: T;
        lead?: T;
        sharedLabel?: T;
        sharedTag?: T;
        privateLabel?: T;
        privateTag?: T;
      };
  route?:
    | T
    | {
        title?: T;
        lead?: T;
        stops?:
          | T
          | {
              stop?: T;
              id?: T;
            };
        note?: T;
        image?: T;
      };
  boat?:
    | T
    | {
        headline?: T;
        body?: T;
        specs?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        image?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  included?:
    | T
    | {
        title?: T;
        intro?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  boutique?:
    | T
    | {
        headline?: T;
        body?: T;
        image?: T;
      };
  founders?:
    | T
    | {
        headline?: T;
        body?: T;
        image?: T;
        ines?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              photo?: T;
            };
        antonio?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              photo?: T;
            };
      };
  faqSection?:
    | T
    | {
        title?: T;
        lead?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  email?: T;
  formEndpoint?: T;
  whatsapp?: T;
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  meetingPoint?:
    | T
    | {
        name?: T;
        addressLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        arrivalNote?: T;
        mapsUrl?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        google?: T;
      };
  bokun?:
    | T
    | {
        bookingChannelUUID?: T;
      };
  cancellationPolicy?: T;
  legal?:
    | T
    | {
        companyName?: T;
        rnaat?: T;
        livroReclamacoesUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-occasions_select".
 */
export interface SpecialOccasionsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro?: T;
  ideas?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}